name: drestaurant-scraper
on:
  schedule:
    - cron: '0/20 * * * *'
env:
  SELENIUM_URL: ${{secrets.SELENIUM_URL}}
  DATABASE_URL: ${{secrets.DATABASE_URL}}
  SCRAPING_TARGET_URL: ${{secrets.SCRAPING_TARGET_URL}}
  LINE_ACCESS_TOKEN: ${{secrets.LINE_ACCESS_TOKEN}}
  LINE_ADMIN_ID: ${{secrets.LINE_ADMIN_ID}}
jobs:
  build:
    name: scraping
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose up -d
      - run: sleep 5
      - run: docker-compose exec -T app python main.py
      - run: docker-compose down
